// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
let squareVerifier = artifacts.require('Verifier');
// Test verification with correct proof
let zokratesProof = require('../../zokrates/code/proof.json');
// - use the contents from proof.json generated from zokrates steps
contract('TestSquareVerifier', accounts => {

    const account_1 = accounts[0];

    describe('Test verification with correct proof', function () {
        beforeEach(async function () {
            this.contract = await squareVerifier.new({ from: account_1 });
        });

        it('should return true with the correct proof', async function () {
            let result = await this.contract.verifyTx.call(
                zokratesProof.proof.A,
                zokratesProof.proof.A_p,
                zokratesProof.proof.B,
                zokratesProof.proof.B_p,
                zokratesProof.proof.C,
                zokratesProof.proof.C_p,
                zokratesProof.proof.H,
                zokratesProof.proof.K,
                zokratesProof.input,
                { from: account_1 }
            );

            assert.equal(result, true);
        });

        // Test verification with incorrect proof
        it('should return false with the incorrect proof', async function () {
            let input = [10, 2]
            let result = await this.contract.verifyTx.call(
                zokratesProof.proof.A,
                zokratesProof.proof.A_p,
                zokratesProof.proof.B,
                zokratesProof.proof.B_p,
                zokratesProof.proof.C,
                zokratesProof.proof.C_p,
                zokratesProof.proof.H,
                zokratesProof.proof.K,
                input,
                { from: account_1 }
            );

            assert.equal(result, false);
        })
    })
});
